sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nag23101990/react-test -f ./client/dockerFile.dev ./client

script:
  - docker run -e CI=true nag23101990/react-test npm test

after_success:
  - docker build -t nag23101990/multi-client ./client
  - docker build -t nag23101990/multi-nginx ./nginx
  - docker build -t nag23101990/multi-server ./server
  - docker build -t nag23101990/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nag23101990/multi-client
  - docker push nag23101990/multi-nginx
  - docker push nag23101990/multi-server
  - docker push nag23101990/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-multi'
  env: 'Dockermulti-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-242610718642'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY